apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: builtin-blockpool
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 1 # 3 para Produção
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  clusterID: rook-ceph
  pool: builtin-blockpool
  imageFormat: "2"
  imageFeatures: layering
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true

---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ceph-s3
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 1
  dataPool:
    failureDomain: host
    replicated:
      size: 1
  preservePoolsOnDelete: true
  gateway:
    port: 80
    instances: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-bucket
provisioner: rook-ceph.ceph.objectbucket.io
parameters:
  objectStoreName: ceph-s3
  objectStoreNamespace: rook-ceph
reclaimPolicy: Delete
