apiVersion: v1
kind: Secret
metadata:
    name: unseal-keys
    namespace: openbao
type: Opaque
stringData:
    InitialToken: ENC[AES256_GCM,data:1Qy8cFDdTY/mCKk/S84p0GSYDs9v3KnjDfo=,iv:DP95ztfppXbSfGSOo75SuXR4GbYsQDmBv0kRhzp0t9o=,tag:fXGefzMA6q3twEFA4So5HQ==,type:str]
    Unseal1: ENC[AES256_GCM,data:YPYhilTD12iA1TiF6dw4UZAeH5f3XMLjdvqUDRvp8j6ksScGw6LBCAeiPdQ=,iv:0Ny2mSQLqLVLB6J+LVbzWwlshhOd42Ev7JHW5Ok5sGs=,tag:qXpDoLU+uyEGKTXJiYVWzQ==,type:str]
    Unseal2: ENC[AES256_GCM,data:37PkR98Dz2UxcAn0eqrAUlCr8X3aPWLjtYGtzA5ZjTkEYA9LpL8SxP2v4QE=,iv:tQSaiN8GCxF/+ZcUdsn09rFJbxuwSTGUxZZxqzEPsE8=,tag:of+DZ2SfueoPa0sf81COcw==,type:str]
    Unseal3: ENC[AES256_GCM,data:BaSBKrJdxLzX71KlY7OPTssa7U9WkHw4nKGljETLso9p8T/mpPRxKII3fkg=,iv:yiA2zJAQrRibJIAZAXBTq060ddLRJQAhyvy8eeuZVRU=,tag:P84+1i7uoe34GbgixBNdhw==,type:str]
    Unseal4: ENC[AES256_GCM,data:fhXSw42rfhltwyHwtke9dExxNkDkIUHkja0HuI4fFNUR+WaILgULoJnGG5I=,iv:EPg/NtdPSvccu8ZKmG7OHd3vFVKS5wqw0HWmnwfzS30=,tag:USN99VYOUztkgDc6dlGuJA==,type:str]
    Unseal5: ENC[AES256_GCM,data:CQuplPKqNmdJiptjsokxEyf9IlUqZLcVyeyDAxXEGSa1yE47QAnpP2zlPLo=,iv:+5q7w6/eqjdMjOc19QrbCBStWMNaoFVBLR8fTdI6uYo=,tag:zKNoBAyhhNMeHgiAPcsewg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGQ2RmhPQlQw
            MUJoUFlXV0hGVEdKRXBEQW1qTURocStKT0kyTVR6NERlUmNQUHVkY25nMUd3cTFK
            ZUxDaTRkdU54R21CYUptUk53MFJpVG40MnJybkdPamhubXArMHNTOEsrblgvSi8w
            WWxTczVuZTBGcGtFUU1iZGtzaFhhRDA1OEEzSmd6MlBvbnRNTzBTdForSUpXQUFx
            Y1F3RTYvblRnRkxBOXNFMXFXbU5kMnJUcGVWOThHMkNJTXIvSjE5aGNJcGVjdTdB
            d002V1lzWEp5TU5hajNzTUVhcDJkOWNJM2tpWk1pdjFuRTNNclp6dHNaV2lST1RM
            L2VZUlMyVHJuYVpwOUZMRE9hcGFaem5ycDc2dFQyQXlzNG5WclJLdVMwekR4Qm1w
            NWxLQjNGQ2RySEsvdUcxdUV4alRxeWV4UVZ4OFg4eEpTcDJldDY3ZGRmODNtNjkz
            Y3FwUTRTYVovdWkxRG8xMmJTQ0hTUUpNN3FwMngxLzRhVjJoV1Z1ZmlPMHpEc0Z0
            N25pYzhSOFZEek1vZU1qeWVPV2l4UUNLZjlRVUNTR1BxWjZ4RWR1YU1WcnBFSWdW
            Um5mMFNoOGQ5eTNldnpFR3RYOE1zakFOcTFNTkpISXRkVERXRTAzeUYxdU1XTmQv
            L21CQ3VhYzJSQlpTVzY5T2RTS1hyKzk0WDFReU5ZcnI3NTVCNFpnY09lcHlKbXNw
            T3JIZWx6ZkF1MWZiVU9waG9BcS9VWTlLUWx6N3V0M2FUWlM4L3hZTjIxNnQ2NXRr
            REIveGlMWWxNQU15Wm9qeEtBSnJ6NU1wU213T09hZ3hxQVdPM1lOSFl1NVVjdWhM
            ZksxbEVRU2Z1dU1BZ1NrS2NWb0tvTWpSSjRhTzBBaDE3THo3T2h6L29IMm9mNEpp
            Q2pQaHJVeUd4Zkl2YjlRRnBFVTVQc051TzlMNklqaEJOVGZWOUFlQjVPNGcvNzFX
            Ti9iV1BBelRYQnBzdGVkekN1YnFGMzlyNmRTL0ZGa3BkUzhGNkFHVllZYnpGUHlK
            bEIxZUNtQVhBb1dLV0hQVXVTS3FkVjFRN0NFNGF6NE5KZFlvcUI3ODBOVkJGNkk5
            N3I0NWxabzRFNXdFZldxQ0pmQTdIMjVwZXBHMkQrV0hTNksrQ3JiemdJN0RndXc4
            bExPOExJVlhIRTlNa0I0bEUvNVpnWTcraXYvaGFQWWYwZDg4ajNValB2eTlKU0Jq
            Z2xxcG9UK2xFemwyK0NJYXZ0N2ZJRHZNdUc2Y2JEOHFuTWNLanEzR1pTK2drc1hJ
            VlcwNGtkSTFsaFQ1dU5mR2VKa291TjgrbkZZNUlFdXpRRXhPdnVFOHJHMHNkMHZL
            dmdJVGU2T0ZLUnZsbVhyY1JkajIwVFNJbGFUUFB1MngrUWp2V0JBN254UWpIaEZK
            clFUdWFXOHRtN3g5TXphWVBuUkM5bWJyUXZPM3ZHdEtRWGNzUXBaMUQzSnZiRTd2
            UnN3cnM3eFZ1Qy9mT1BiamROaXlmWG9ISGFGVmF1VHpxVkRsaStBL0Z1eVE4QnAr
            V1hYSWxOeDhXQ1NZUHE4V0M4TVN2Z3VZMUVmTVVDZGNISFBaK05ZZ2Fxc2dYcHRT
            WE5EbFVjSFQ2WXI4QUNHWFlTd0VxS1VkcUpoREJlWkRWYk8rYWRlcXE1aW45N2lH
            YXJod2ExVU4zbUNvUm90SkZ1bWhjaldwZ0dOcnR2TU9HT1JaWG4yKytLT01OcWMv
            WllxMk9KTkc4aFRMcmVGYnZQUFl6cC93eVE1czRINmJZQUFjRVlJR1FJemNMWTR4
            eFVSQWkzQXA5QUxSNi9mTit0aUl1WE9ITGtEcW42bWhaenhrMEhDWk1GTmVzTXA4
            aHozeFcrd1B3dXdWd1pxZHE5NUpRWlNLODhyQ3dCWmVZeWRxbXpqUjNCWXBlaGRt
            VDFVU3BobklkaFR0b3BTVXdMZWxOa0F5TkRqaHJZWnIwNzZ6U0dTdUdVaEVYUQo0
            cElMVW1EOG9hcG5XbWtzaTV2ZXhqb2NkcGZyc0pSUW1DQklpdVBGUGFjCi0tLSBt
            WUxFVHJreFFGbzR2eTRRRk9PRFdJVGJXYTR5RXJUeWxnTnVpeXZyYjhrCo+QjoY0
            XrvT1+sUCHRJs6IAtsKOhJFze3XyCNNO8a18rwJKXymSdbQ53PRpmrkXswAebijE
            7raxRe8x42ZDjQI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1fm96eas2guseckhkr9z0cwqs62szyfd3zyfasc0vwsztkvpss02etcrjz9w9qrtapgfxzwc4nq66cp25v7pu5dptas9hheu5ahazjal6vrkxkx8v8st2q6dy5x2fsdr9kvk8twcdr96ttemhujkfm5qvfm22suhmswggzfn0uqfchv9xeuelk6w9qc642q4eadrzh3lj52zuw3k7lqs8w9z2s8gzv2pzekc558f99q7mgedvzup30u4uw36aht06uywpj2j4pm5tmvs9kja0k8wngs42xjgwu6n99gf98jjz3q5zy2pge8pu2qjcezp2xn52kpa5zz0fuz37xm29axjgg4z5s66fq2avvlycqeegmggm8k9wg0n48x2nyvqktjusw9eu0knq49ydykv8z2yc82tzv6n3nn2krnty9vx6mamh5a24kmqp9arkxu2gzly8ygux6k4n3cskkf40w58fuc62ftp8ma6hdtpy8ssyk8p592pjnf60n8pz0x6hpr45c4r7788dhaudeky42r3k8sxcp893hj6aavmgpqftpmte4vj0dxjeuf97apktp7tphp05ngurz804w4waaxcv994z2qjxfszx8namp3ccquch9qx95egnws4nchwxlvwpw9cul6ftnl2ef0g9zlgpkp4q89qz58eyw7g9nganf32wmqvv893zawasjy4s0v2t2hd3tsvn6xjq6jgg88uq9vvfrfkef8p888r9f4c56ghm83r9ky2ppsrh3x40jl448d7zd4de2thpnscxgee242ptmqmjnl87jw6gsjjhyumwnmsug5zedxxd8p2y0wltnee4tyw9jg3nxvpe9q4dljrdm7m7swj9anzsgectgx3zudvp95pdnjc3yppcp38wxx5asfa4ahqfksngpqz2x922rv8rjklnf55ft8rk2y73nh9pcew30j5rgcmatltj8v4zxxxazqllafy4ezjpfv6m4jlcvgfzxk59fgm60gx2qrpe536yq3h2kw9hysthc4vv6emy2f9mn8g80yde2ynags2pmey5n48k0ulzy0sag3sqfk9ku0v9xadt2k0g9n20u6fq8cns4d5twt23kp9yxrqrt9numy9cuxcugsygdwn9q5xyuqx2c9ffcfz55crq33gc3wqpdg4cz5mnzet9zkrz4hf4g4p6ngdtmy5wh5wy6wa948dp42cnxn9tdesfeykq6wxedrqlrznw6zkpz7ffy6n25rwntyjqqns4rqhssefljmavpdusn8rgx9tj66j86vddzepmpf6hsrtty350v6cevysyde2tndrgg38sq0dc0v8y63675pz9a68p0w6jc994k8psad9gwcc3c83tf82scep2xxf5jpnh073vt3q9hdsjqmr0t28luxge6nwqnusctdsmzyfqvdcp2faem24vt4ajeqgcgjlpgjduwa9gxt9jk0dckkecs2u50x60vumjzwe5y9nhztweyqacjqhke3ut9k2ykhqm3up0pg9pvrzup8zeew6smqa9gjahs6jyzw8g8cthvk5ylj5jphzz2fhn6gw8uf30f35sllf3xdw8cdawazz3wf9pmxgjma2crm872nycnqch7xzdc4mq2kdex5jvtpl6x3p374uyttuc8ml25w2jk9cpep36sfm0ssctr6ry5frvyy0zk5kwdve2syre834m8m2r27qnj305jgacdrc2f00n2g0jkltsygl9xvpydrwg67q59ekxtvd0ldfnkjr63nqymzk6ggjp33hkxqhfapr8zcxyf7qr0dv6w26ynytcmut9qqjt766fn8p62ttn3tzaknk5uhvzuvrr5fqs33jldxkjwfsaseql8mqwqlwyxheg6s5fvgggqfsq7rsrvrgcmhl026stqsf770sqaj76l9sekur7l209qhl30svqzvqf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHdSV3hMbkh5
            enFGOUlSN0pWQS9GYjFzZmhhL2dvaWNrbTlJaE0wbklxeEtxRmx3WUt2NXBKeUJl
            aVhKeTgxMmFTRHF5blVCbG42WFZONmJpZEpjMzlZSktkSENlbS9lRFBvaSt3R01W
            N2MrQ0VzNGdYL09lWW9mMXNKRXBBVnVqUUFXQjhwYnowVHVaK2xyNkgzdDVQT29D
            bFBpNWlBQkxzOFRQV3lUeEliRGZmZUo3OUJlbUdzaWx1U1YrUHd2OXpFd2kxTWVB
            amZISE5ua21qSVV4TmUxMXhDYnNPY2tzR0NNZTR3ZFU0UlRIOVJzUjJFcyt4dmJY
            M2xyaE5rcjJ1YW5pMTZJVEJaRXRsK09yRHdHY09tVTB5bnBwZXMyQ2lBWDlySTZQ
            bDhZSEd6UUpBclVEZVJqL0NLNlpVV0RCQ2l1ZXViNW9Zck9GTkQ5WU9kYlRIaUhH
            eVFLZmdrQ0xDanVEd1kvQWJ6T2E1cmhXTFFBOGtSL1hFdVZwMTF5TzBINzFmT3RP
            TlVDM29zZjNvZDBxL0pucVBtMk85ZWJDZVVOSXJheXMvRWxQamtxNXJiQ0JGVzZM
            VVM3Y2ZiY1BMVXQ4T1lQTGxHQ1FnUWcxdk5pNVFvSEVGK09KSy9wdjV1a1l4eFkw
            QlRTeDJyRzV5U01kdjRZM2FDY2FGRE1aVituRStZZzdPZVdiVjRVVnRRV1VVN2to
            NERIcWk4Wlc3NTBkdWo0U2I0a2tjbTN2TUhDMTlnQk1FZ2F4WjY5YmtYdEdvSlhH
            ZnlkRm9rWFdCelpuRUZzVklkek9mVktTTkd1NDlQNUhwSDdlNVIveks1b01pUFp1
            dEV3eld4T0VSN29TV09kYjl3ckRPNHY1dnJwWGVCQTNCRGxxb1NzN0IwWmYweDNL
            Q0ZOMWdzL3h6WE9YT3F5elpmL29hT3BvWEhEUE56dy9Ja1QzWXlIZldXeWJibVRK
            VW5XczdHMUY1ZkFPMXNhVGJQZmxZTUdhQWJsVHRRVWpVS1N5dlJ6VjZvWVlZb2FT
            TlMyQjRNY29GSVVxZ1ZqV25sMm9EZjJ4MU5rTE13Wm1Nd0hnNkxJalpJYThXaTlR
            NVdvdndIeGt2eWh3Wi82eUxMNnZmMktvN2MyTnFMdlNNZGpkTTNkeDZoVDFkWkhl
            SSs2VUQyRTUvbkZXajM1TXRkTzd5UUtQZEFxMG9MWVJscEorUkdqV0QvSjdpdXhV
            YzFFWHA5UEZ3MEY2SEFPZlRhbjZPRFllZVpZeDUyU2ErbklyU2xyeW1XVnQzWWI2
            RkZRTnJFVEZQb01PaEhyMUE1Si9YVzBFb0JIb3d1eVJWV2NWcDRyTUdicXFvMEpx
            RVpOZmxhbCtGZHVmdHRjZzBSMGE2czB3eU1PRXlSY2VId0s4Rzh0Rlc2NmxQZnVn
            Wm9sdXRyNW5hRExmQWc1Z0FBSmlXTTR3eGFmN2dXZFpGc1lsQkNKTERrVzI5R2hp
            alJnUXgxMGw0dlAyeUZIcGdEVlgveGNyTFFHUE04dDFvLzY3eUJwSXRLRDNKbXBj
            UmtBZ004S3VLQ0FWZURDS1RxZWlUOFRDMGJRczhPSE5ZRHpQOHpJNkc3VjJhVm5v
            MHhPU3pYRjFOOFpnU2gwbEVucWRjOGhab1laYWRsWTR5Y2dlYVZBSm1pMXJDZ0FT
            a0lBNE9RN05GNS9EdmJqaGtCM0J5YmxhWUgyVnRsTjdkR1FiUnIrZlE0TnBkSStW
            dUd2bkFYTkRHek9DdnBpeDZWQjVSMTVSbGZ2cy9vTC9mK29mRjRVcVhjQzAyWldN
            UlJVWmRWNHpFdlBVeExKUWFrdTNQWml3bWZnTUs0WlFJVW0zT01KclVCazBnS1N3
            RGlNbktqWTRXelhQZFhRazV1RTJYMGhXWS9WZHl6bGNJakRNSzYzNEpIcGNRb1Bw
            dXVQMUI1eFZPMmcrRk1wVGhibkpEWkZXSm03cHdkeG9ZWGwycDd5NjJPZlZBZwor
            RldvQ080aGxUS3I4cmljM3pmaXkxRGx3MkZOMGtyaXJnS2NKamU5KzZjCi0tLSBy
            WHAwTjJUSWxRV2t6UVhOMjk0SmFvMXdSZzdaVk15azU4N1hMSWdsVWVFCgFX7SpD
            /beUpSlMODf52W90HEu3BDTxQRQxyux1ZL3ptRQ+dQFjOhCh+lCVegozXjNdP8fL
            5EE0OazSWh7F5HA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq18wvpuzf4ng4cpyykvjypanzusm5u9shgd0f9tsesgs8seaxdql9heejys4hcx6z055t5nxnsg22ntwqc9yw4twev8szvrs7tel3gj3cjvxrqzmmpf2zkqsuvt43590v5w5qph3z2dggd4vy4q6f4fagukw4p096q2fat39t0w5cv6usk27aevucc2tpyye38e258yyqjw7kpnzc0d2s2futjkqcvwgpnd435su607unjvg2n6syptwzccyvyv9q64g9pte9j9djcrv5er2e05tan7v9pt7zmm5trf8ufwclj9qvjxyu5mfqem8umpty2crcggq79v6m88kfankpxfqtxt2yu0yhwxfp3rqda40nrhtcpkv6aq82qvuu0wavtlv5pz4wkcm7meflj4wr0f6qac35ueqsvr5tjjtt3rxqj4yvemn449lr6nhyp5fzf76jtrqekcnr43g2n9t7f0ncrukezek35cwzjmgeepk4gewhy8n8g8qg9kgu8umltdsnzwgtup9l9h6cvf2vnz8urhf05xpv58pw8ncelh9p6fc8xe0wuydgs5demcgrgczf8ga85tsdrxeqzxdalspyllwffdux2p2d7hjtvh9sc7jq4nu3fyrj80wje5syu6tptc8qrt2p4j4rg95hk5alwc5glacx2hjgjc8dgdxelrjh5wt8jrv5dsj9mg4gvnlpq2uaxsym23ygvres2z469yvtxevxu82rv6mqczgrrga79rygnqk9nlwx6u2z95pgqrrlsc87csw2r2qmna35xctd38spr9e2m0gwanglhp6jqh69c3a0fclj8xtr2a3xmk6aeerprkrd6qzwc2s0s83hylsc3u33p8glkn04lvmr3lzj5ly3nemjjxt8n466nq9tlqskaq9s7czqhgl8kx02egzpsw9mrfvrp3vtsgwdrne433qahq4h7vlrv53aq5c33gvdpe9ylrjfcy67dn4ycpp09sh0hwzc4xknnp2nwux23xhqz02jdj6hx6wcmnyc7mhyynrpnjxg4rvhdq2qfeyrjg0my5nggty36n95jvhych4a59znxzzagk2ek2ht024cpzn946ey6djaer8t2v4j4g5fuqpss8ed2zly5pc4xkgqxydrp4ukx9fae0navzsnadqln750knyudden2e5z4na5uxr8znqp95kq5gg7vwr0v9fayhvh42vpywkqzy6a23ztmhwuqsney9v88c29qlmskpv75y4ljtvssdfl3acdlggz8s0k3wp24y33y5a8x8992wfdh0889t9ezxxqwssdha2ymz64xg3m64u788wga59d9ckpqp6e4rjk5w86x4z4tsdzu3je5z4y9sp7p8ys54xxx82un04e79nduq52zhkthtqn4drp4u2ewx34fssfeykaqsrg0k2wj4znt0hpqlhaksyqd6xn2wmz8dzrlfjujqckgy9pnzkmn9366s9aq9ugs4w2rjk9s5d3fg97p3wz8mqyv92f38eedyg482yyt0jkx3k7pjdk6288jy3u9kuwc8g9rn0gmu0mrqhvmrsg9rd5chjp8fr6e84u3zn43k4klrv06uyq9naf5nusk5vtk0d55xvglq499c8pyt5zmca29xmzsgwc2tfktuvqv4qjh90m7pt709dhfq3puj4ax77hn4tdf3skhrfe3m4zlgpzrm53f3sqwcyjs2s0sxd6lacyns5q5su380n4kmqmdu6vevuevms5xs7jsgy4s3zajg79dlznmlexzgr65k4quwemntfplsc9gp7yn0cx08jhls2dxq7cq5aqclqtyf8ddvs3g6wrsszecnqdm0ctstc5jdglfakywrx4k8qs6wyra2e9xjz6l40fhl0ttm70kxkva0lw2wpxczm2ardgcc4s3ce5zlz05kz0jarmx6q5ky5nhajgw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T19:02:29Z"
    mac: ENC[AES256_GCM,data:oOCPlVYPZ7zJHY79i65P5uZL5Ls7z9XuWI6t+dxkJsge50/l5M2GK/PO3S9capqtqXCLRyz4MNqYuCjSfvy9wEyTwYw+448qHdzvc3xSrem+bU48ZEhhYGE3EKzZh7fkwIqi9ruVdVIgdphFQmiaHp5NHOB74MvwNNXGqbEOA8M=,iv:n4V4vXJzBgfhWdnN4ao+qdgg7yuAt3D1BMXcg1pZFME=,tag:Y6FOUV9kJLcpBuJZ3ChMPg==,type:str]
    version: 3.13.3
