apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: velero-backups
  namespace: velero
spec:
  bucketName: velero-backups
  storageClassName: ceph-bucket
