apiVersion: v1
kind: Secret
metadata:
    name: security-test-secret
    namespace: default
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:fXcCTTmMB8TCDYXATx5Dbqhv05WKlL7Cwx3S7ZADzA==,iv:XAcdfMap7NQeyY7JDgFIsTGSpw4krG5ZxwTBCtSq1+Q=,tag:rNOOxm9c3X3+KsHujGRdYw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    key_groups:
        - age:
            - enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHlwQWJlM2sv
                b1dqRXM2cWljRzZ5WmNyR1QrSk9Kc2VsK3l5OTdncjZHZ0FVanpueW5Bb08zaDRX
                Tnp6NnZGaWEySW9JL3NMSTBVZ2FBUnlNcVVPaGpGaG0vaVhobUZuMnZxOHlEd0pa
                VEd0UUcxUnhyeW95UTJSNDhmcUlTa0ZVbWtrdUcxWjFrMCtyYURMVkhUcjI2dzJs
                KzlXUHYvMWZBNWJKbDlmTmRFY1hJL0x4aURJQVdrakJzTE15TDVXQ3BTcGNaRTlj
                NlU1TE1mSXN6VTJsNzVqbVhSSHU2cFA5YnJ3a2NMOFZobWl1YkFGc0ZoY3BHVG0w
                QWpualpKRFZ2czdDbkpjbmN6WWgvdTdUYS9iUzc0REdUVjQvcnFwOWNkay94cit0
                UUpwdTY3ZHdEdEhuaE45L1dkbUNxNUc5NHdJeDhjbFAzbDhvVWExN1VGUmtVSGlX
                VnY0VS9oWDdxZG5nU1lTVldPZ3FMSXRWZkFqZHMwOGJsWjNqV1pVYVJLYWExVUIw
                aWE5dThCaWhWc0hlOXlIRGJLMjZFMzFWaURtbUVWVkRKYkNtZ29KTlMvMk9jWFR4
                ZHF6ZllwSkZ3RmdvY3hpK01aR2tsTjNlQVh5ZDAxK3N3S2tJK0RKZTN1NWVFNlRN
                UlRIVkVrOHY3VHF2T0FrN05JSFE1TlNLdmdBWmtQTW1nNFIwQkUzMEQwVGsyck1o
                TzJYeFZLaWttUE5FLzRweElSSXB2cUJST3VnbklZM0NJeERxc2l6YVpWVjQrREhP
                dHFUbWZ1dWpsQlFYbjdRWVFXeHl2RjZYQW96bmlTQlowSklRVUptcEY0U0hwdm1z
                OTcxZEwzRWQvNGlRS0dlTzdQOVp4R2YyMldzMlhnUmtPMXl4cnN2bkFRWSs0Ni9W
                aFpHQ3NpTVpmbHE3Q2NZU3lhR0FTWGEvVGRseFFXWVhlVXpsSk1PbTdXV3E2dWRC
                N09wTlZWWTRMUXFqS2hVS2pES3NRV21QN2R2VVNNWTJUS1F2bVduYkV6MmJtOFNN
                azRoQk8rVXVYUjVxaEtpeFNNNllFVVZkb0RtTUJQV21rNS9ORGlJMi9xNmh1SEtt
                cHVvYUd3cWpUeS9PM2c5dkVpMDlTQ3A1TklWYnlSVEZNcWExSGtQNHUzdlVweElO
                eGVybjQyYlY2cTJYRGZCVFBHUWdBVUUxd2R5b0M2RS9EblNVc2hvaWdwWGtJckJ0
                OXMwdjUxSzIrUUFQYnZiU29ueVNqWUZxMjAyN0wvelJIMzIrK0pBeUk2eXRuU2kx
                YWJDMGJjTlYySWpEcUFkaHcwUUxjL1JNcTZCWHZTVm9WbTFtNzlPS3FsQ0R4REQ2
                cUlBa3NUMU8wYnRNY3g4OVFXTjNBSHg2Sm05V0VuaEdRenJWcFdValVVNG5QV1gy
                cFJUb0x0dytuclJsQnliM253d29wcGRBOEdFN0hkWWxQK1VFSWd4cnBWVlBHbmJ1
                SW0vRUc4bVJqL3ZIRlpGdGE3YzBSTDlKTzQxeXhuL0xoQUdSWGFySDdMcitXK3Vz
                TXNFL3duOUEyVzltWEtOYVFyTHF0WXFZSTlCZFZiTG9nZWdraWplMkIwWW0zbTha
                TXZtOGlvS1lsczRFNi9HTS9yOGl1SUR4emFITEx1UEpEYlppV1pySnU0YjNYYWpw
                bmpReDVTUzB4L21VM2cxcmt3WXYveGFQTVpOOUloeWhFTWtSQnBaMVA4VHg2OVN1
                QWpqU0NqS0JEa0N6d0ZKMzE3YjlJdlRiTDFxVEVYY2xzQ1doRFc1L04vQmJZaVR6
                N2RNaitNUDJIajEwYmRybHVKN1VlZTk2WlZRRTRDQlhkbkR1V1Fwbzd2L2g4bDhK
                dXUxeEZZSGJYVlV5bjJ3OFhLY3Z6QVpHRVdlOGNZblJKRVR3K3V5bjZaU3NvR2hN
                VUVPSkhYWVNRcUR4dFJ5Tzl2cHZmcDBXNklFcUdHUjdBQWMrdkRvVTQwQUlRUQpO
                ZHlDZmF0ZXd6bStLOS9KTGlwbXFlWCsvRy9ubi9TR3M0ckc2aXFGeUdzCi0tLSBl
                T3E5aERrZ212a1FBMEFLemNsaWcybW9ZVHRaMHdyQ2Nka2p3YUEzRWNJCsj7w6jZ
                18BJ4qMg2A/JzIuHtrblRKRwbeDrw9NFV1j0ZXYLEAhIF6MZU+bD4nHUQxGy3BRc
                Wd6eXIxqL69Op+HX
                -----END AGE ENCRYPTED FILE-----
              recipient: age1pq1fm96eas2guseckhkr9z0cwqs62szyfd3zyfasc0vwsztkvpss02etcrjz9w9qrtapgfxzwc4nq66cp25v7pu5dptas9hheu5ahazjal6vrkxkx8v8st2q6dy5x2fsdr9kvk8twcdr96ttemhujkfm5qvfm22suhmswggzfn0uqfchv9xeuelk6w9qc642q4eadrzh3lj52zuw3k7lqs8w9z2s8gzv2pzekc558f99q7mgedvzup30u4uw36aht06uywpj2j4pm5tmvs9kja0k8wngs42xjgwu6n99gf98jjz3q5zy2pge8pu2qjcezp2xn52kpa5zz0fuz37xm29axjgg4z5s66fq2avvlycqeegmggm8k9wg0n48x2nyvqktjusw9eu0knq49ydykv8z2yc82tzv6n3nn2krnty9vx6mamh5a24kmqp9arkxu2gzly8ygux6k4n3cskkf40w58fuc62ftp8ma6hdtpy8ssyk8p592pjnf60n8pz0x6hpr45c4r7788dhaudeky42r3k8sxcp893hj6aavmgpqftpmte4vj0dxjeuf97apktp7tphp05ngurz804w4waaxcv994z2qjxfszx8namp3ccquch9qx95egnws4nchwxlvwpw9cul6ftnl2ef0g9zlgpkp4q89qz58eyw7g9nganf32wmqvv893zawasjy4s0v2t2hd3tsvn6xjq6jgg88uq9vvfrfkef8p888r9f4c56ghm83r9ky2ppsrh3x40jl448d7zd4de2thpnscxgee242ptmqmjnl87jw6gsjjhyumwnmsug5zedxxd8p2y0wltnee4tyw9jg3nxvpe9q4dljrdm7m7swj9anzsgectgx3zudvp95pdnjc3yppcp38wxx5asfa4ahqfksngpqz2x922rv8rjklnf55ft8rk2y73nh9pcew30j5rgcmatltj8v4zxxxazqllafy4ezjpfv6m4jlcvgfzxk59fgm60gx2qrpe536yq3h2kw9hysthc4vv6emy2f9mn8g80yde2ynags2pmey5n48k0ulzy0sag3sqfk9ku0v9xadt2k0g9n20u6fq8cns4d5twt23kp9yxrqrt9numy9cuxcugsygdwn9q5xyuqx2c9ffcfz55crq33gc3wqpdg4cz5mnzet9zkrz4hf4g4p6ngdtmy5wh5wy6wa948dp42cnxn9tdesfeykq6wxedrqlrznw6zkpz7ffy6n25rwntyjqqns4rqhssefljmavpdusn8rgx9tj66j86vddzepmpf6hsrtty350v6cevysyde2tndrgg38sq0dc0v8y63675pz9a68p0w6jc994k8psad9gwcc3c83tf82scep2xxf5jpnh073vt3q9hdsjqmr0t28luxge6nwqnusctdsmzyfqvdcp2faem24vt4ajeqgcgjlpgjduwa9gxt9jk0dckkecs2u50x60vumjzwe5y9nhztweyqacjqhke3ut9k2ykhqm3up0pg9pvrzup8zeew6smqa9gjahs6jyzw8g8cthvk5ylj5jphzz2fhn6gw8uf30f35sllf3xdw8cdawazz3wf9pmxgjma2crm872nycnqch7xzdc4mq2kdex5jvtpl6x3p374uyttuc8ml25w2jk9cpep36sfm0ssctr6ry5frvyy0zk5kwdve2syre834m8m2r27qnj305jgacdrc2f00n2g0jkltsygl9xvpydrwg67q59ekxtvd0ldfnkjr63nqymzk6ggjp33hkxqhfapr8zcxyf7qr0dv6w26ynytcmut9qqjt766fn8p62ttn3tzaknk5uhvzuvrr5fqs33jldxkjwfsaseql8mqwqlwyxheg6s5fvgggqfsq7rsrvrgcmhl026stqsf770sqaj76l9sekur7l209qhl30svqzvqf
          hc_vault: []
        - age: []
          hc_vault:
            - created_at: "2026-09-18T19:19:20Z"
              enc: vault:v1:wNo+nSnL0vmOCnxhAaNZBZbZZnLMLgKCIgIEBcZvNY71lOJ0BsaNyrM+zNs3z2pS4LKIBsUBgttV8vrXZA==
              engine_path: transit
              key_name: sops-key
              vault_address: http://10.0.0.134:30200
        - age:
            - enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IC9CWG8vMFVu
                aWovWUljNUZQWE12WllSVWNNYlhaUFF1YTZaUHNlL0hUNnJjM3RTZmdyVTJnaGw4
                WEdjeXJYa1NscWt1a3RmV0N0OEVPa3d2OEx0UTRVNlViV1RKSjI5dkxlb3NKNHVs
                MUlPenNuc1loSjl3cVpjV1pzaDlqMWo4dVlmVDlzbmVSVnRjQjZvUWh4NVh3cmxT
                bWdxN0V3clRjd0V2RzlheFJMTFl6MlRlck84V0c2TDZtVjVoY3ZZKzZ2OGJ3V1M2
                RXU3cTNLdzVzU2tHL0NzRHF6dG13bnhlVDFvaE9SNkNDOS8vcXoxZzRoN0s1R2l3
                NWFQYXhwVGZGR2NHTXh6QzVzMCtnQ0NmSE9iUU5mT3g3Vnh0dHFvVmZHTFhrRU1p
                RjhQSmtORnQ3TjdiR2x5aHkxU1p2UEltM2x4NnozU2xzUjJqRzJhelBRZzZtN0VK
                K2p4aW10OVROOStGa2twSGwwNXZtK2Y0RDBESFh4T1piQ3RVdDZZOW1idjRxVkJE
                L2dyYzJxMWJNSE90YWNreTAyY2hSTTh5azlOT2o1SUlpYi9nMFVYWkx2Y1liRU1p
                TDZJQ05naG5FUnpNanBZbjVrWVdmT2JLL1ZVRkIxWmE1WE1aSVBMcmU3bUk3T21a
                dUNOWEd0VjFmbHdNSE1YZmllYmVHMS95N01mK0I0MzJrSlNKWUNJV1ZPMUhZT1FP
                OTY5em1vOU1wQnp1STkxdld0aUtWc0Q0ODRhRlUyNnUyQkJqRmxoZnRYWjAwWVRG
                TlNkKzlxY0plUEFmNzA2WkFHWUt6Q04zWHJHM1JwR05NS0xHcmZxT2RQazVlejJp
                LzVSZ2dxS01iQ2M2WHpIbnZabWwrQ1ZVVEFycmE5cGRiQmVZT3ZDRTVWZGZ1bEwx
                RnF0UG1mejZTd1pLSGhWOGwvRE9CUExhRG9qSDJ0WGZCNTdaSzRmUU9vcktZZTdt
                UTg1YmJkd2FBMXJveEROSnNST1BmRXhuUEtBcVdqcytrT2VJWDhLNnQ5ZTJaYTJk
                aDI5SVpMQm9oMkhnRDJsaG1idk45bURoeldQMXlTcmxlYllqU1VRVXFLc3IrZTla
                MmpVaDZ1cjhRWTZrZXhFc2pVK3lRWGYySjdTR1N6UklNRGkycmlob3FZU0lKVUll
                ZTN6dW9jR0ZCMFNBSTFKZWJNTkxuL1VuZGsycWRha05la1Q2R1hwWGtBWTZEd1Rp
                MHBITVo1MzRLZk56ZzFrOWR4SVVXeHphVjFtQm1tcERzU1NrT3U3cVpWUHd6M1lY
                dU1oSTNDNHZqcHdMMSsyc0MwRi9MUm9wK1ovd2VRVUFjL3ErYyttRGtidmNNaThy
                MUwzMXUyY1dqNDhMU0tKeFVMb1A2WVlMelVpQUtZeEN6ZkxnM3cydnpSQW5YNEtD
                MFphMUVMTW5xZzdOZ1NqdWtuM2NqWjZYVEc3WTIyTzhaUDFRd0F0QTU5REJ3Mm5p
                Qlc3NVJsMDJ1WmVqTzB5SHpxV0Y2WHhtRWFIK2VVR3JEOHk5b3JHQ20zV2pVQ1Iv
                elppbFNOaCtKeVRRSFI1OU9pVjd3dHdOTjdwY0NwM2FGTmZXc081OVJSNmNrWDB5
                MExpbkE1dEtXZGpDZDh0ck4yWXEvZEdYYjRPcHlNQ2lobUZRTnFsdEhIb2xVZXY5
                aWVMSFJ5L0F0WGo1U2E1RnJwVFdZUHJTQ2hQN0grMWxheEtzSkNhUlpVekFZNDE1
                NmxqM0hja0h3UDdXbW85RDNpdkpVUWFOUzlldE5KTVJWek81UC9nOFBzOG5zODdJ
                UEJodWlVQktteXlUbzMzekp0LzZHMFlOL2ZKa1F3MHN5bGRTMmxyVjNZRXFkZjl0
                OGZmUkc4blovZHNmOEhFN2NRamFsclJma0RrWEJHU1d6QVNhclRVYURaNFRGMDhQ
                V2lvVGIvcXBYN0RkQVltUzM1UFFGUDRMSVpKSXF5OW1DTXRSRU1McmpyeWNmUQp2
                M0E0L3lNYVljNG1nWnd0RC90M3BIaWZxT3FabjdMclJCNFIvRXlTdmZvCi0tLSBr
                TXphaHhzSDdhMzkya3p4VzJIK3NvendCbWhJekN0d05HSXZxWm85cHQwCmAX5C2f
                P5n1Z87VjERIkfudYkvUoti5QwlvBqzk3E83QkxjSpS9q1BQQ/UhW/cNN8PqvKA/
                hf3p3F3bBL/9KwhK
                -----END AGE ENCRYPTED FILE-----
              recipient: age1pq18wvpuzf4ng4cpyykvjypanzusm5u9shgd0f9tsesgs8seaxdql9heejys4hcx6z055t5nxnsg22ntwqc9yw4twev8szvrs7tel3gj3cjvxrqzmmpf2zkqsuvt43590v5w5qph3z2dggd4vy4q6f4fagukw4p096q2fat39t0w5cv6usk27aevucc2tpyye38e258yyqjw7kpnzc0d2s2futjkqcvwgpnd435su607unjvg2n6syptwzccyvyv9q64g9pte9j9djcrv5er2e05tan7v9pt7zmm5trf8ufwclj9qvjxyu5mfqem8umpty2crcggq79v6m88kfankpxfqtxt2yu0yhwxfp3rqda40nrhtcpkv6aq82qvuu0wavtlv5pz4wkcm7meflj4wr0f6qac35ueqsvr5tjjtt3rxqj4yvemn449lr6nhyp5fzf76jtrqekcnr43g2n9t7f0ncrukezek35cwzjmgeepk4gewhy8n8g8qg9kgu8umltdsnzwgtup9l9h6cvf2vnz8urhf05xpv58pw8ncelh9p6fc8xe0wuydgs5demcgrgczf8ga85tsdrxeqzxdalspyllwffdux2p2d7hjtvh9sc7jq4nu3fyrj80wje5syu6tptc8qrt2p4j4rg95hk5alwc5glacx2hjgjc8dgdxelrjh5wt8jrv5dsj9mg4gvnlpq2uaxsym23ygvres2z469yvtxevxu82rv6mqczgrrga79rygnqk9nlwx6u2z95pgqrrlsc87csw2r2qmna35xctd38spr9e2m0gwanglhp6jqh69c3a0fclj8xtr2a3xmk6aeerprkrd6qzwc2s0s83hylsc3u33p8glkn04lvmr3lzj5ly3nemjjxt8n466nq9tlqskaq9s7czqhgl8kx02egzpsw9mrfvrp3vtsgwdrne433qahq4h7vlrv53aq5c33gvdpe9ylrjfcy67dn4ycpp09sh0hwzc4xknnp2nwux23xhqz02jdj6hx6wcmnyc7mhyynrpnjxg4rvhdq2qfeyrjg0my5nggty36n95jvhych4a59znxzzagk2ek2ht024cpzn946ey6djaer8t2v4j4g5fuqpss8ed2zly5pc4xkgqxydrp4ukx9fae0navzsnadqln750knyudden2e5z4na5uxr8znqp95kq5gg7vwr0v9fayhvh42vpywkqzy6a23ztmhwuqsney9v88c29qlmskpv75y4ljtvssdfl3acdlggz8s0k3wp24y33y5a8x8992wfdh0889t9ezxxqwssdha2ymz64xg3m64u788wga59d9ckpqp6e4rjk5w86x4z4tsdzu3je5z4y9sp7p8ys54xxx82un04e79nduq52zhkthtqn4drp4u2ewx34fssfeykaqsrg0k2wj4znt0hpqlhaksyqd6xn2wmz8dzrlfjujqckgy9pnzkmn9366s9aq9ugs4w2rjk9s5d3fg97p3wz8mqyv92f38eedyg482yyt0jkx3k7pjdk6288jy3u9kuwc8g9rn0gmu0mrqhvmrsg9rd5chjp8fr6e84u3zn43k4klrv06uyq9naf5nusk5vtk0d55xvglq499c8pyt5zmca29xmzsgwc2tfktuvqv4qjh90m7pt709dhfq3puj4ax77hn4tdf3skhrfe3m4zlgpzrm53f3sqwcyjs2s0sxd6lacyns5q5su380n4kmqmdu6vevuevms5xs7jsgy4s3zajg79dlznmlexzgr65k4quwemntfplsc9gp7yn0cx08jhls2dxq7cq5aqclqtyf8ddvs3g6wrsszecnqdm0ctstc5jdglfakywrx4k8qs6wyra2e9xjz6l40fhl0ttm70kxkva0lw2wpxczm2ardgcc4s3ce5zlz05kz0jarmx6q5ky5nhajgw
          hc_vault: []
    lastmodified: "2026-09-18T17:15:22Z"
    mac: ENC[AES256_GCM,data:HdQ5P73uHfr+t69XXWG9Ww+E6NZuWyPZQ0Op1iTsl6dhTw89D7RapADfk4UuUH9vbQh1XkYRFdFN45tChPk20hXbGFN7nwbsC4IEFVE1lkWfm4SxwJ9/OvqhE6dksAZXErL/UM8a0dzLZ06v1FiNkVC3wcd0kti4pJwYJIYS8wU=,iv:d//omjETPZnwiIbJJ+YDW3vIkl/Iz7ONnnp5CvR2cFg=,tag:tZCDs/0gXc07DNKJtbB3Gw==,type:str]
    shamir_threshold: 2
    version: 3.13.3
