apiVersion: v1
kind: Secret
metadata:
    name: security-test-secret
    namespace: default
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:fXcCTTmMB8TCDYXATx5Dbqhv05WKlL7Cwx3S7ZADzA==,iv:XAcdfMap7NQeyY7JDgFIsTGSpw4krG5ZxwTBCtSq1+Q=,tag:rNOOxm9c3X3+KsHujGRdYw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    key_groups:
        - age:
            - enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHN5Yk1oSmVp
                VStVd3luNmtqOWU4RlgwalN5R0J1ZkJGeFYxM2ZsTDdJb0luS0hEVDlEY0dkaEJS
                RlZ4ZDdwbk9vM2ZWTHUrQW9NcmJPbytpbzEyc0IycWVGNHZFRDdkazFQVVpndDBk
                RkcxRDNmc2JiaUg1YUl1YzFVNHhIaDdNZHhZSHZWek82UXZyWmRRYjcvSFY4alZN
                TGVUTThyQXBTVEZ1RWhPdy9nRlVyLy8rQjBNUURVMUxCanB3SkR2ZXlkQnJzVEln
                My94dDJOaitCN1d3S09VUmJHeGtOVVdlUkY0K3NzeG9JcTZ5Z2k1eVF5ajNrNzd3
                SHdHMHBqdTdWOUcxYmdWenlwN24vcDVHUFdJN1FXOEx6a21GVUQ5YjRRWnFFcGNl
                d2p0WWluRTloL0pxYjA3M081aVJUTW0zbUdvSjdPSDE1RExoRXlKc1k4L0VLTzla
                RXNZMkZzS2tIWjdIUWxNNkN2cjQ5K015clFWRE0xbTVUNGN1SkRYU016bkF1cEUx
                UUNIYmlNWXJUL1V5ODVtMWlCNC9YQ1VYaG0yQnIzWGlWcGpyVm5VSVhZYktTc3BE
                dGRTQ2RmcHBTTkpkU1o2R2N3SWVRS0Fqa3ZjQzJHSEloUVF6a3NvZktKNDlqeS9E
                QnFJY0JEcWhLbWNKQlBXbllncnloSFZlS0RVbERXSEwrNFRTZGQwdDIxNHlSeGlK
                ZVYxRTl1MG9KczFOMURWRFdwVHpYbGw3ZmZVUlJ6NUtvek5Lb0pxOTA4R1FqYVFz
                OUlvS2JwMTRocW1qRGVEUDByQUJ1QVk1RFkyUUdCTlBxTkZ4bEIrNG1nQjVnZXBi
                T0tWUGVnUXJTUUVDTTN6a0p0WDBQMFlkcVF0Y2FMUkJ1aVh2a08vNERXanNIeWdl
                VXE4S0pDTENPTzZpVmFnYWZFaldXZ1NndHFEWHJZckwyaFFuSTFaSlZ3a3o4Rkp1
                bUpJL2RTQUMxVDlSaitLRjlKZTNlQlprUUVNMzd0WWJyeEpxdlVqVG5XTmRSZTRP
                NkdvK1ZJY28vLy8xeEVUMXZqcThTMjI5RTlJRVRVWGlET2VTQVU3M015V09ZUktv
                YWhPODREQUJJd2tGZ2JOd2tleE1td2hNemgrVEl6VnhqWnRhMmdBdFN6eGpYaDB2
                YXE3UTZGWnFDVXNsYWxhUmFjTGlUakhSZ1lSZWphbXRaM0tFeDFzc1lNRWVKWHJ5
                MnJ2U01NNm1sOUJONllLRm9ieDFUdzRaSDBKSmNocXlHRlRFK3UvdkNNT0dhdmxi
                dTBqYWJyeFlVTmgzbXJKbWlvL2g2SHBlTW0ybXlMb1k5Tm4xZFVvbzF1dzhoblUy
                V3VjcENGSkNFL3BFWGlVdGx3dG5EbnRUVCtRcXp2NXFHQzg2R082MGdBK0s1ZG4w
                YXJTTzF1QlJsK2tRMStEYW5sSTRkZEhteTZ2R1Z4a0JjL2JUSUwwZWU1YjdyU3d6
                UXdRUTFWRHZEd3NhWXk4Y0NIUXJqQWxqSUxjV09GcWV1cGhtSWx3SmJHcjdnVmtS
                dzYycnNVbGdXRTRjaG5aRHZSWFFIZWpSdElBRHdYSHJYUlA4VitZc3VReC9oUkxl
                T2JyUlNsUXVSNjZBWTFDR3VIYnZ2UnYvU1hFRlhuUmllZWFPQXB6VWJUNEJjN05M
                RjdUV1Vza1RrdjhXSlMzV0FvQkNMT3ExNmRXVkZRRHFFNCt2ZjVsQ3c1MTl5eXhq
                eWNVeVh5VjdOcVZ3U2toTHppU2RRTTc3ZHJVRkluQ3FwMmt0bHZBRkhLU3ZLQjEy
                TVUrQjFMZ3NMRCtSL1JzeE5xRGdMczBISTU1N29YRGhHaUVjeStuTnZjYXhXbHh2
                WkJjSUJXM0pvSzdDZTJ1MlFYbXVyK29ZL2FIR1ZyQlFyQkFSSVBqN1hMTkdUUFgr
                RnhtakgyVk93NWVPb0FDc1ZTK3dUWWhqVVdDWGdhYTNNbGhHQWZFVFNQTkVWUQpG
                Uzc2MzJrZkF2S0pNbFZwa3UwSEk0a2N5VWVHWUZBaW9tcXJaTDdhT21BCi0tLSBp
                b2NZUUtieE9DSkNZaVJwdmpBaGxWd0ViRjJFRUR4Wm9QYjFCcWVQS3NJCjDRi1Sp
                V46bgyleOfN49ReWifxwzd2fkf3eYwAekuhx2wAdqkBmHf+kNcTaT0g+k6mwvm1d
                IXSvtP+oyXLE4tGi
                -----END AGE ENCRYPTED FILE-----
              recipient: age1pq1fm96eas2guseckhkr9z0cwqs62szyfd3zyfasc0vwsztkvpss02etcrjz9w9qrtapgfxzwc4nq66cp25v7pu5dptas9hheu5ahazjal6vrkxkx8v8st2q6dy5x2fsdr9kvk8twcdr96ttemhujkfm5qvfm22suhmswggzfn0uqfchv9xeuelk6w9qc642q4eadrzh3lj52zuw3k7lqs8w9z2s8gzv2pzekc558f99q7mgedvzup30u4uw36aht06uywpj2j4pm5tmvs9kja0k8wngs42xjgwu6n99gf98jjz3q5zy2pge8pu2qjcezp2xn52kpa5zz0fuz37xm29axjgg4z5s66fq2avvlycqeegmggm8k9wg0n48x2nyvqktjusw9eu0knq49ydykv8z2yc82tzv6n3nn2krnty9vx6mamh5a24kmqp9arkxu2gzly8ygux6k4n3cskkf40w58fuc62ftp8ma6hdtpy8ssyk8p592pjnf60n8pz0x6hpr45c4r7788dhaudeky42r3k8sxcp893hj6aavmgpqftpmte4vj0dxjeuf97apktp7tphp05ngurz804w4waaxcv994z2qjxfszx8namp3ccquch9qx95egnws4nchwxlvwpw9cul6ftnl2ef0g9zlgpkp4q89qz58eyw7g9nganf32wmqvv893zawasjy4s0v2t2hd3tsvn6xjq6jgg88uq9vvfrfkef8p888r9f4c56ghm83r9ky2ppsrh3x40jl448d7zd4de2thpnscxgee242ptmqmjnl87jw6gsjjhyumwnmsug5zedxxd8p2y0wltnee4tyw9jg3nxvpe9q4dljrdm7m7swj9anzsgectgx3zudvp95pdnjc3yppcp38wxx5asfa4ahqfksngpqz2x922rv8rjklnf55ft8rk2y73nh9pcew30j5rgcmatltj8v4zxxxazqllafy4ezjpfv6m4jlcvgfzxk59fgm60gx2qrpe536yq3h2kw9hysthc4vv6emy2f9mn8g80yde2ynags2pmey5n48k0ulzy0sag3sqfk9ku0v9xadt2k0g9n20u6fq8cns4d5twt23kp9yxrqrt9numy9cuxcugsygdwn9q5xyuqx2c9ffcfz55crq33gc3wqpdg4cz5mnzet9zkrz4hf4g4p6ngdtmy5wh5wy6wa948dp42cnxn9tdesfeykq6wxedrqlrznw6zkpz7ffy6n25rwntyjqqns4rqhssefljmavpdusn8rgx9tj66j86vddzepmpf6hsrtty350v6cevysyde2tndrgg38sq0dc0v8y63675pz9a68p0w6jc994k8psad9gwcc3c83tf82scep2xxf5jpnh073vt3q9hdsjqmr0t28luxge6nwqnusctdsmzyfqvdcp2faem24vt4ajeqgcgjlpgjduwa9gxt9jk0dckkecs2u50x60vumjzwe5y9nhztweyqacjqhke3ut9k2ykhqm3up0pg9pvrzup8zeew6smqa9gjahs6jyzw8g8cthvk5ylj5jphzz2fhn6gw8uf30f35sllf3xdw8cdawazz3wf9pmxgjma2crm872nycnqch7xzdc4mq2kdex5jvtpl6x3p374uyttuc8ml25w2jk9cpep36sfm0ssctr6ry5frvyy0zk5kwdve2syre834m8m2r27qnj305jgacdrc2f00n2g0jkltsygl9xvpydrwg67q59ekxtvd0ldfnkjr63nqymzk6ggjp33hkxqhfapr8zcxyf7qr0dv6w26ynytcmut9qqjt766fn8p62ttn3tzaknk5uhvzuvrr5fqs33jldxkjwfsaseql8mqwqlwyxheg6s5fvgggqfsq7rsrvrgcmhl026stqsf770sqaj76l9sekur7l209qhl30svqzvqf
          hc_vault: []
        - age: []
          hc_vault:
            - created_at: "2026-09-18T17:15:22Z"
              enc: vault:v1:PACYt/EKwGqHHlz4NdLY6d5irjge/La/3eLO2PkrQzSsbNj0zEX15PF8pISBGSfDEtBrXOR/pxQEi/M5Gg==
              engine_path: transit
              key_name: sops-key
              vault_address: http://10.0.0.134:30200
    lastmodified: "2026-09-18T17:15:22Z"
    mac: ENC[AES256_GCM,data:HdQ5P73uHfr+t69XXWG9Ww+E6NZuWyPZQ0Op1iTsl6dhTw89D7RapADfk4UuUH9vbQh1XkYRFdFN45tChPk20hXbGFN7nwbsC4IEFVE1lkWfm4SxwJ9/OvqhE6dksAZXErL/UM8a0dzLZ06v1FiNkVC3wcd0kti4pJwYJIYS8wU=,iv:d//omjETPZnwiIbJJ+YDW3vIkl/Iz7ONnnp5CvR2cFg=,tag:tZCDs/0gXc07DNKJtbB3Gw==,type:str]
    shamir_threshold: 2
    version: 3.13.3
