apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-repo.yaml
  - traefik-release.yaml
  - cluster-issuer.yaml
  - ir.yaml
  - middleware.yaml
  - dashboard-auth.yaml
