# Pra declarar onde vão cada coisa

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik/traefik-repo.yaml
  - traefik/traefik-release.yaml
  - traefik/cluster-issuer.yaml
  - traefik/ir.yaml
  - traefik/middleware.yaml
  - cert-manager/release.yaml
  - cert-manager/repo.yaml
