apiVersion: v1
kind: Secret
metadata:
    name: unseal-keys
    namespace: openbao
type: Opaque
stringData:
    Unseal1: ENC[AES256_GCM,data:mLT3BjYkP29+3Kv45+7ZfaRWvLDzVqa21ZEI9Lo7QotZfwX+PxLgDb+B13E=,iv:UxpESyAvitPffrQeBpLk9+NZQWvmfUMR5X77sVDdShI=,tag:Icf0IyQ/75LRl7xPyVw02w==,type:str]
    Unseal2: ENC[AES256_GCM,data:nshl/Gz0XcjkvDHsK61oe1ivpiOlUWg3y60TCdF/XaidwwAfP9lRGJgKloo=,iv:jZRANf4hdRtFZWR0nCbZ6GPpvYXkQBGJwk2z9zLYbkE=,tag:YBK3eGTSHGLf3PNmAUTtHg==,type:str]
    Unseal3: ENC[AES256_GCM,data:xpWWOXfgl20VPj6KfzEdkGJzc327Pxfkpr8kqlZQ+IOjwrjbs6JEPXsf3DY=,iv:CJvI5kJP/E3oVvv+ABe1FluNNGmVHtbOkVM+Q/RafOY=,tag:yWB9/lx5bTe67H925yta2g==,type:str]
    Unseal4: ENC[AES256_GCM,data:MoQlpB0MH6D++H206noenI0zFs9NebPxOadpy2YEJyXOVsFcqjEDjmyOOWo=,iv:3zzbgFTM3pvth86WZE8EaazJrTE37njbeDrI7iO++Z4=,tag:axD5K/xdn3hmRnV04cbwQA==,type:str]
    Unseal5: ENC[AES256_GCM,data:zfbl70IlnRPvZ0J2YpPYyW+pMAXbhh9j9iFu8GSlSgSD/jYYU1F+c/LKfn8=,iv:ox5I0HkZOrDV00Q33hgGB9EwOA0sXMwtGgue3zLkO/Y=,tag:A69texCJDVXZlev2ztpeHg==,type:str]
    InitialToken: ENC[AES256_GCM,data:WsyT5quGvcF/gudF2HzgAMfNihxOAgTBTRA=,iv:eTLltjI+G1LSBsZ/zeWh7YUL87mHCjrDQGlREdkO0Tc=,tag:L5947sRqbYY2KPV5eyJlBw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    key_groups:
        - age:
            - enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE9tRm91bFZi
                ZVRCeUpsMW0zdS9VejViT2VIeVBqSzZtOVVtZTU4RVdFY2Qra3ZvdUt6bHNQK3gw
                b21sUkRvSWRUeDhJZG5tMEkwM1RwaHNuWitGeWpHaStaU2p4VDFvR3hoT0tPOXd4
                eWxuNVIwR0V3M1p4MVhlaUh2Y2hzTm9mR09qUnlMV21qNEV2ZFoyM2xCTUVVZTd0
                NzhMaUlvNEZBd1cxZzhjOTQyNFhvaVA2anNDb2xDc010bzJsMUd4RnlER2lCN3NV
                YUZoR0ljQ2w0aWdqK2N1YXE2ZUpWOG9PWnAwdHhyRTN1aEFGOTRTYXpxa3dYT29n
                Z1BmY21sM3d2TU55ZnRnZ3pXdEVCRFZWYi9YVU1ZUVB2S1U4SGo1eXVKODIvRTg5
                TEZMUThrdWZSMTJ6OVFBLzRvWWhuQkFpZkVxZFZsY3dpREFyeUw5bVU0MCtOSEN2
                d1NEMkFWVTAzdy8xaEtFdUVKV0ZYV3JaaTZLUEM5dUNKdWw0bFZXK05qYUthZTJq
                ajlXSlM4YUZ0U2FZSnR5N1R3Tm5kRmwwWlgwSzY2cmlrbG45RHM4Y0hOa1d0UUI5
                N01tdzM0WmNKbEw2Mkdxc2ZPREJDWmxmdTBIN09kQVhTaThJUlZIRmdpQkFsWXU0
                OUVkT3NLZE94L1kvazNKQjJ1WnNZVGN3Ym5FU3F2WFpKWEx3Q3hVSkllSHZEYU5u
                ampXeVBCWXJ5S25PcTFFQWowNHBtdXpZdGZNeWx2YnkrZ1RYR2lrUnM3b3UxWmRw
                dmFUbXk4b21hRzN4Nm43VGY4ODdlWmtXaXN6SHo1NnhrS1l6aXBqWWFiNWxlaGNl
                MDhPQnNCQUZFejFUeWF2VFVHTENPa2pKMEF1SjMwY1VLR0ZuclB6eGR3VzlZQ0Q1
                TjR1OVNxSzJNM28yMTB3bXVnWUdhQXpBL016QW5PT3lZdHlPREx4akw3OE5QNUtt
                eDQza2prTzBFaXlPekR2K0tlTGo2ckRsRU9QeUZCWm1DbytkZEp0VlNVUFN1Rndh
                ejJVZWtRb09hRHl1LzZ6aWxEL3BBTDRzMm11YU91dmlsUXZqSHYwUlFaVXpseERa
                cHhCa2dkcnJEQzBaTXQxYy9sbmVMU2prNWxpQTBoMnRpZVRUQXp5WlExdXdDWmxV
                VlFxNTlrNFN3OTNsMmhnWG05VXlzVVBXMDNpNnNmYmFFK2tULzR5VFhrTkxoWEhn
                SHY4Qy9lOW1kS2lydDZ3YUU1QWdtMlRVVkU3dXVRRWlWZFd2YmpoQnVoRzAveC9n
                WDRnVzM4OGVLVng3alA5Z21wbzUzUnFuaTJ4aHdNWG1JRFNCb2ZrUk9hTW43U1RK
                ZVNoMVVOR0pwNjRiMmFIVFFYRUgrOVo2bHdSYTlxQTB6YjNpTUJCS0lwWHk4SmlD
                Z09pR2dmRktYdkJsSk1hOEY4SXpkRmxuSGNkbjZBRDVTcHVabEkyU0o0d2lieGlQ
                V3JNT2swQzlCeFF2NysrM2VJeWVlSlpxTHNTSHJOVmJxZExZbUtEWTRDQlNCWm9L
                OFNnN21PZGdtbHJjMzVyUkVNUHc0bCt0ZXVjWW9xWG5odGVkM0lUNDc2SjIwakFY
                cVZXVStSQ0plNWFNNXNGMTFSMnNnUi8wMlNWRkcweWllejFxMnByVVdmRmtXYkdM
                MnRpUG9EeUlHaEJPemRKY1h5ZnpzNXIyL2tBN0hIbnN2eDJiT1cvZDJvRFY5UVlN
                enBEZGR0OG5ISzlRN201RHN4THJZZ1RSZ0x4anhUaVFqS1JsaVprcVpYOHBRdDdV
                T0MrT2E3bGFDYVZ2c3NJaC96UFdqb2Z3VEZvaEx0N1JvRkx5L1FqRzlkbkJNc2hI
                dnBYa3lVcGd2UWxEcFd4MWNKUDcyaEJwOXZORWwycUZuSGNqME1mYVFrcFRZV2p2
                ejEwWjJtSFlyNFczcHdOWlFKd3NLaEtHNXhwN3FSRFBNZXcycDh0ZmxkYldVZwpX
                bm9VVmdOWjFsZU1VU042SmpEc2toRTFrRy94WmRUdGNBU3FRWEVkTmZzCi0tLSBw
                aE95OW51SE5XeVpFbWtzVG5Hak1ubFdkclNKQXExbE9udnk4QlQ0bUtVCiepE9iX
                WgtvHES3+IoMe/R0AZ/ZJy4k671wD3eZAj3WxPwbcG0w8ETojmqbypbaiXav30Xd
                Tpd1hheMLDqBxPlO
                -----END AGE ENCRYPTED FILE-----
              recipient: age1pq1fm96eas2guseckhkr9z0cwqs62szyfd3zyfasc0vwsztkvpss02etcrjz9w9qrtapgfxzwc4nq66cp25v7pu5dptas9hheu5ahazjal6vrkxkx8v8st2q6dy5x2fsdr9kvk8twcdr96ttemhujkfm5qvfm22suhmswggzfn0uqfchv9xeuelk6w9qc642q4eadrzh3lj52zuw3k7lqs8w9z2s8gzv2pzekc558f99q7mgedvzup30u4uw36aht06uywpj2j4pm5tmvs9kja0k8wngs42xjgwu6n99gf98jjz3q5zy2pge8pu2qjcezp2xn52kpa5zz0fuz37xm29axjgg4z5s66fq2avvlycqeegmggm8k9wg0n48x2nyvqktjusw9eu0knq49ydykv8z2yc82tzv6n3nn2krnty9vx6mamh5a24kmqp9arkxu2gzly8ygux6k4n3cskkf40w58fuc62ftp8ma6hdtpy8ssyk8p592pjnf60n8pz0x6hpr45c4r7788dhaudeky42r3k8sxcp893hj6aavmgpqftpmte4vj0dxjeuf97apktp7tphp05ngurz804w4waaxcv994z2qjxfszx8namp3ccquch9qx95egnws4nchwxlvwpw9cul6ftnl2ef0g9zlgpkp4q89qz58eyw7g9nganf32wmqvv893zawasjy4s0v2t2hd3tsvn6xjq6jgg88uq9vvfrfkef8p888r9f4c56ghm83r9ky2ppsrh3x40jl448d7zd4de2thpnscxgee242ptmqmjnl87jw6gsjjhyumwnmsug5zedxxd8p2y0wltnee4tyw9jg3nxvpe9q4dljrdm7m7swj9anzsgectgx3zudvp95pdnjc3yppcp38wxx5asfa4ahqfksngpqz2x922rv8rjklnf55ft8rk2y73nh9pcew30j5rgcmatltj8v4zxxxazqllafy4ezjpfv6m4jlcvgfzxk59fgm60gx2qrpe536yq3h2kw9hysthc4vv6emy2f9mn8g80yde2ynags2pmey5n48k0ulzy0sag3sqfk9ku0v9xadt2k0g9n20u6fq8cns4d5twt23kp9yxrqrt9numy9cuxcugsygdwn9q5xyuqx2c9ffcfz55crq33gc3wqpdg4cz5mnzet9zkrz4hf4g4p6ngdtmy5wh5wy6wa948dp42cnxn9tdesfeykq6wxedrqlrznw6zkpz7ffy6n25rwntyjqqns4rqhssefljmavpdusn8rgx9tj66j86vddzepmpf6hsrtty350v6cevysyde2tndrgg38sq0dc0v8y63675pz9a68p0w6jc994k8psad9gwcc3c83tf82scep2xxf5jpnh073vt3q9hdsjqmr0t28luxge6nwqnusctdsmzyfqvdcp2faem24vt4ajeqgcgjlpgjduwa9gxt9jk0dckkecs2u50x60vumjzwe5y9nhztweyqacjqhke3ut9k2ykhqm3up0pg9pvrzup8zeew6smqa9gjahs6jyzw8g8cthvk5ylj5jphzz2fhn6gw8uf30f35sllf3xdw8cdawazz3wf9pmxgjma2crm872nycnqch7xzdc4mq2kdex5jvtpl6x3p374uyttuc8ml25w2jk9cpep36sfm0ssctr6ry5frvyy0zk5kwdve2syre834m8m2r27qnj305jgacdrc2f00n2g0jkltsygl9xvpydrwg67q59ekxtvd0ldfnkjr63nqymzk6ggjp33hkxqhfapr8zcxyf7qr0dv6w26ynytcmut9qqjt766fn8p62ttn3tzaknk5uhvzuvrr5fqs33jldxkjwfsaseql8mqwqlwyxheg6s5fvgggqfsq7rsrvrgcmhl026stqsf770sqaj76l9sekur7l209qhl30svqzvqf
          hc_vault: []
        - age:
            - enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE5vL3JRbUZq
                N1NvMGpicGhKNENXM0tGRm5lSTY1c1AwdHVrUVg5QnVGcHhzNDZiQ1JVTFc4QXBR
                MU1TOXg1bnhiV095SFlUbHpZUXdhLzRNMS9PU0JkNkxxQmh5WXZ0bDY0T04va1A4
                eldxelEzWlRyTFBGM1lTaGlidFlpeHJHQm81SkJDU0JRRmI0YjNwWWFYZCtvVUZj
                TkU0T2thcVVURXByZ2RjR3ZWcVpUMVhsZVZkTnZjaThaVFd6SmlyZTdLNlB6cFR4
                d2M5RnFvUUhINXhWbE0rWDN5cmQweWU0eEtIclQ4T1A5bHN6Y0lmak9lWkNnSGhQ
                WmF4OTZYbHo3c2ZPVHJYaFREQmE3WVVMZ0w5aWFiRFcwZWtlcmVURlRtSnFiOVhL
                ZW9PS1BXclFoZ2hIODl4K1R1Qmg0S2JrQkltUWV3bFJacTR5ckJhY2F6WnU2NnJm
                OFhWYUNxbjVHTU8zOEpIRmFuOGpsWXJPd0dkdlZDT2FrcnlRTENYNkJyclNyL29P
                elU1NFl2VG81bXpOL29NQ1g0ZGZuSVVFNjhHdlppaWlTM0hjb2lzbGd2NC9Kd1pq
                U1A3UUxmMHd5NjQ0L0hQcGpVVW1heGYwUTVnemk3Q3I1d3llTGdhQXFta3JYTmxs
                ZDdYamVCVnY5MlZMMkpoZWp4YWhNditDcVZsQm5ZOXI0UENpdDRVMllMem1NbzM1
                RkVKYXEvNnhnNVBRTkxad05nWDdYNXJ2bi8vdHV4RkRxUlZwdllhMUJjSENkMGsr
                OVB1MVNhRHRWWmZqVjE5YnNJODB2Mm5zYWFMZmVQcGhHbk9xTUIvWmxRMm1Gd0l6
                amlORzhxNTFNNHp1bHpSMVU2bVNTdzNtY290MjB0UWxWcXJQVVd1Tk1DUFk3N3Ru
                eTdRcndvckwyRFNXRVNrcGxwaEhFSFgrN1kyajUxSC96WlVBTWtRa2VXcDZZdWZJ
                T2FWVnVKUmtOZWlTRit4S1hxY0w1N1BwTEEwenYyRU9oTjFjazR2SExJbHdzVWsy
                eXhoRisvcHMrR2VnRFUydi9Edzcrd2R0TElhVm1JWFFOdlN5RmxobTBsQld5Mlhv
                RUw4TmJnL1lFYXpsRzdTMkxyZDhDWUZoR3pMcG9JNkl4cHc1ajVVL0s2M3MxUWxh
                MUtBTndOc0hFOHFnK2FGMDFmUHhGSkM5WE9RRkowMlNObnhnVTM4d1p6am1EZ25W
                azhSZGRjZnlsaXJZNVJ0UXk4R3VTTVpTbm4yLzNURzFzRCtQQ3FFNEhzY0RCdTMz
                UnYzTDNVS0VTWlUyK1lzQmhOKzJsV0ZZUm51MThBalhqSjY4TWJMYnZUWFBBSi9X
                TkV3SEpXbUhaMXp4R3NDZDNxUzQ5UWhWMk9WRWVqeVVLNE1rNVFWZzh6RjNLeXFq
                bk9naXJIUUY1Sk5Qd0U1bEJVN1BkWjB2c0xYaXlaV2FNNk8wcFd2MDFvTTdhN0Zn
                U0E1UmpIUWx2RTkvWUZJdkJZOTIwWWl0aklBVHRoK1o0NE90cUlLVlI2MVpmUUZM
                aldpdXZ4N1dXUkpkVHlCbjVkbEp4MGc3ZE8rZGxwbUVmbGVBeFF1eHpyRFQxd2dP
                OVhOZnpQemVWWXpVN28yYWhEOXNzS1d1T3M0R0VLSUdNeW5NV2c5WmljcWZkdnVn
                NVBCcGlZcmMycnBxRXZNWTN2b0tEamxkOUhsU0ZWZ2p3RjJURUxTOUFtN1RjWHNt
                V1JGdEpYRVhxLy9jYmJvODNWajQ2VVp6RXFOSnM2dk9BYy9IVUZBSDRwTlA1aEFy
                eCtPUHYycTAwbnJUalhGR3BoZmFadlZqV3lGZ2cwVDZEa2lHSnRZb3RWWkFmN1Q2
                VXdUd2IxQjhJMmJILzVKd1VrcGhTdjFiM2dzWWorYWErOXNsQkV2N2FKWDgxVDV0
                WGdpb1BuQ09Sb3ZGLzNXWW9XOUJpa1Z4UkNWbjlmVHhDK1cxUXJPQ09xaDRNQQp3
                SkJpcSt1S3pOd2hDYWUxZVp5ZHVmd0hXdC9YbmFTbERjTjVFeFNON1NvCi0tLSAr
                Q3Q2Vml1Nk1Dblp5V1hraDdVY2tjU3M3NTR2M3dac1VCZDJFK0ZsenR3ChmNm1h+
                5MdCisPAZxF8hMv1LO29kUKJIZntTOVNew1HWajXvwRxFMzxDq5/fPF6PMmqrDBV
                hQFS6EAeqZR+V1sS
                -----END AGE ENCRYPTED FILE-----
              recipient: age1pq18wvpuzf4ng4cpyykvjypanzusm5u9shgd0f9tsesgs8seaxdql9heejys4hcx6z055t5nxnsg22ntwqc9yw4twev8szvrs7tel3gj3cjvxrqzmmpf2zkqsuvt43590v5w5qph3z2dggd4vy4q6f4fagukw4p096q2fat39t0w5cv6usk27aevucc2tpyye38e258yyqjw7kpnzc0d2s2futjkqcvwgpnd435su607unjvg2n6syptwzccyvyv9q64g9pte9j9djcrv5er2e05tan7v9pt7zmm5trf8ufwclj9qvjxyu5mfqem8umpty2crcggq79v6m88kfankpxfqtxt2yu0yhwxfp3rqda40nrhtcpkv6aq82qvuu0wavtlv5pz4wkcm7meflj4wr0f6qac35ueqsvr5tjjtt3rxqj4yvemn449lr6nhyp5fzf76jtrqekcnr43g2n9t7f0ncrukezek35cwzjmgeepk4gewhy8n8g8qg9kgu8umltdsnzwgtup9l9h6cvf2vnz8urhf05xpv58pw8ncelh9p6fc8xe0wuydgs5demcgrgczf8ga85tsdrxeqzxdalspyllwffdux2p2d7hjtvh9sc7jq4nu3fyrj80wje5syu6tptc8qrt2p4j4rg95hk5alwc5glacx2hjgjc8dgdxelrjh5wt8jrv5dsj9mg4gvnlpq2uaxsym23ygvres2z469yvtxevxu82rv6mqczgrrga79rygnqk9nlwx6u2z95pgqrrlsc87csw2r2qmna35xctd38spr9e2m0gwanglhp6jqh69c3a0fclj8xtr2a3xmk6aeerprkrd6qzwc2s0s83hylsc3u33p8glkn04lvmr3lzj5ly3nemjjxt8n466nq9tlqskaq9s7czqhgl8kx02egzpsw9mrfvrp3vtsgwdrne433qahq4h7vlrv53aq5c33gvdpe9ylrjfcy67dn4ycpp09sh0hwzc4xknnp2nwux23xhqz02jdj6hx6wcmnyc7mhyynrpnjxg4rvhdq2qfeyrjg0my5nggty36n95jvhych4a59znxzzagk2ek2ht024cpzn946ey6djaer8t2v4j4g5fuqpss8ed2zly5pc4xkgqxydrp4ukx9fae0navzsnadqln750knyudden2e5z4na5uxr8znqp95kq5gg7vwr0v9fayhvh42vpywkqzy6a23ztmhwuqsney9v88c29qlmskpv75y4ljtvssdfl3acdlggz8s0k3wp24y33y5a8x8992wfdh0889t9ezxxqwssdha2ymz64xg3m64u788wga59d9ckpqp6e4rjk5w86x4z4tsdzu3je5z4y9sp7p8ys54xxx82un04e79nduq52zhkthtqn4drp4u2ewx34fssfeykaqsrg0k2wj4znt0hpqlhaksyqd6xn2wmz8dzrlfjujqckgy9pnzkmn9366s9aq9ugs4w2rjk9s5d3fg97p3wz8mqyv92f38eedyg482yyt0jkx3k7pjdk6288jy3u9kuwc8g9rn0gmu0mrqhvmrsg9rd5chjp8fr6e84u3zn43k4klrv06uyq9naf5nusk5vtk0d55xvglq499c8pyt5zmca29xmzsgwc2tfktuvqv4qjh90m7pt709dhfq3puj4ax77hn4tdf3skhrfe3m4zlgpzrm53f3sqwcyjs2s0sxd6lacyns5q5su380n4kmqmdu6vevuevms5xs7jsgy4s3zajg79dlznmlexzgr65k4quwemntfplsc9gp7yn0cx08jhls2dxq7cq5aqclqtyf8ddvs3g6wrsszecnqdm0ctstc5jdglfakywrx4k8qs6wyra2e9xjz6l40fhl0ttm70kxkva0lw2wpxczm2ardgcc4s3ce5zlz05kz0jarmx6q5ky5nhajgw
          hc_vault: []
    lastmodified: "2026-09-18T16:59:03Z"
    mac: ENC[AES256_GCM,data:F+K/27yz3kcQbHPI+rc/QqLACoCPk/ZSWOp04Fnm9bpn7bQwVoCzEEAl1RbbV+S2B4SCayGJDs4IHRP3ltKz6P3AlYooYXdNTk+u13ZBQ9Lg/FQkmmm4hR2t553/3vfU6reuQzaSsC/0Ha31U5tvEtRaJVwkR5Dqd2+gb6sYQEY=,iv:hS9yhRvgh46r+sebA0AApbTvwnByLqKGiuU3ejo1/KU=,tag:LaOUafzL+SYWaXpMQQ3q5w==,type:str]
    shamir_threshold: 2
    version: 3.13.3
