apiVersion: v1
kind: Secret
metadata:
    name: unseal-keys
    namespace: openbao
type: Opaque
stringData:
    Unseal1: ENC[AES256_GCM,data:mLT3BjYkP29+3Kv45+7ZfaRWvLDzVqa21ZEI9Lo7QotZfwX+PxLgDb+B13E=,iv:UxpESyAvitPffrQeBpLk9+NZQWvmfUMR5X77sVDdShI=,tag:Icf0IyQ/75LRl7xPyVw02w==,type:str]
    Unseal2: ENC[AES256_GCM,data:nshl/Gz0XcjkvDHsK61oe1ivpiOlUWg3y60TCdF/XaidwwAfP9lRGJgKloo=,iv:jZRANf4hdRtFZWR0nCbZ6GPpvYXkQBGJwk2z9zLYbkE=,tag:YBK3eGTSHGLf3PNmAUTtHg==,type:str]
    Unseal3: ENC[AES256_GCM,data:xpWWOXfgl20VPj6KfzEdkGJzc327Pxfkpr8kqlZQ+IOjwrjbs6JEPXsf3DY=,iv:CJvI5kJP/E3oVvv+ABe1FluNNGmVHtbOkVM+Q/RafOY=,tag:yWB9/lx5bTe67H925yta2g==,type:str]
    Unseal4: ENC[AES256_GCM,data:MoQlpB0MH6D++H206noenI0zFs9NebPxOadpy2YEJyXOVsFcqjEDjmyOOWo=,iv:3zzbgFTM3pvth86WZE8EaazJrTE37njbeDrI7iO++Z4=,tag:axD5K/xdn3hmRnV04cbwQA==,type:str]
    Unseal5: ENC[AES256_GCM,data:zfbl70IlnRPvZ0J2YpPYyW+pMAXbhh9j9iFu8GSlSgSD/jYYU1F+c/LKfn8=,iv:ox5I0HkZOrDV00Q33hgGB9EwOA0sXMwtGgue3zLkO/Y=,tag:A69texCJDVXZlev2ztpeHg==,type:str]
    InitialToken: ENC[AES256_GCM,data:WsyT5quGvcF/gudF2HzgAMfNihxOAgTBTRA=,iv:eTLltjI+G1LSBsZ/zeWh7YUL87mHCjrDQGlREdkO0Tc=,tag:L5947sRqbYY2KPV5eyJlBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFVBNXZZNmd1
            NVZ1L3pFNXNVaHR5UDF4dFdXU0lqTXExd0U4ZCtrYysrNnZ5VDQvYXlzcGgwYnhP
            NTBVektZcGc5QS9IWnp0TmhZcTdUV2J5SWlXdWpYVUh1bi9tQW5RZWVqZU1qNjlY
            WVRMOGVhdmRvaHJtak5nNDcwSFpTNXhuVTkyNWFiK1Bhcmh0TFdFeVIybnZBSnFQ
            bHp6WjVldStVVGpEWStmVVp1UGdvTnl1THZiVWlyM25pSzB6dDFSTVdoOStHbFdx
            RDJla2poeUl1RUVoWU4xWWpDbVJnaFhnQy9jNzlTMm5FUW0rNExEN0htWDhpOTlO
            b0NUaWY1U0xobG5SeW45RThCaU5GbUNqVTVuRXo5MzdSRlVwTzhuY3hpNjZDRWZt
            dGRpZTl5cGY2SWtGR1FhTkFxQXZKRGVCYjZLbWFFWHdkb0U3UW52RlFaemJaUkNu
            VkhrRGRxaUVBdnIyRTFNT3dmUnpMV2VOaXhjZWtuSXphUExSdFJVblBBNitacTZD
            aVdnQTFKendQNENwd3VkV2lVK2h3UjlNRFNXa3NlM1hVTmVoNjdGb3Z3MGVkSmZQ
            bHJHNXN4YUhRbitNTFkxeDZFM0lpay94T2VPVytyT0NVWnhVQU15WEphZWRXazFT
            Nnk0RFEzTWdUTnB1MGVKQUJDbGlxbmY5cEFhWXdGcUtLcTBqNDZOUUwxYjR2cWM5
            aDc0RGVlZWt0ZHhMZkV1d2NEMTZvOTJkUUtwQ0MrTWtXOFB5cWpXOXJEWHJEUy9w
            Y3N4K0p5WGxBd216UlBYS1RSc2d2Wkord0dXRmIyNldGWk9qQmdoSkdHamdkMzBa
            N29lVy9hdnRnaTBObks3dG9hV1FxREkwNFlnLzRLNkhEVTJremFjNHlpcGhMbzRn
            QkdycEU4cmRWekpUZW0xY2Ziemd4VzlrZ2hUU0Y4M0tmaXg0bVc0andhZk82MTg5
            akZXR2xRYis1UGJBWlYxcTI0UjV1YUV6eXE5ZU5tYVEzd1Y0Z1RvbVFPNVJVTDJy
            NHFTL1VkazBLZUVsdmNYWU9Wc1d5RnpzV0tLb2hIdytyVXE1V1lMYmpKZmdyTktB
            UEtkNjhqSEsyRTMxRG9tK0tCMzhpNjEyaFUzcUNKTCtwRUhTTWg5VmJVb2hBUjJT
            MFlxRnlXWWtjV2ZudWZzYzJzWCtoUU9mZk52NFlQQVRWZ1hqOTRZVHBoaUYrcUt6
            b2VMSk9nbm1QR2lDUUxaWEpid2dOWTBpdjY4NmJyL3ovbTkvL2VtdWhCcWZnZEsx
            cTAwYVdLU25MOUROdENDdHZRQ3BwSUllcFBtOWJxSTRHVmhPdmd1RWVRcXZqcDd5
            REt4c0ZqSXovWlowZ2l3SnRnbndMYkVIZ0Z2L3QxY3pPenh5N1I2bmllb1k3RThk
            U0ZQZW5DTTdoeHhNVTA1RWdQV013cG9jd2ZKOU9GQXRWVXd1cG1PK2hsVENOenhH
            WFp1L1pOaUxrSzlhSWVYTlZmVXI1R2xRNEhGajl0azdwcEpTUEhhUFZ3Y21vY3Fk
            YW9wL3lic01CQ0dPUWU3bHN1RGVSVk5tRnRTbmpjdWdFZE5PelpEVTBmaDd3VW1S
            WkhKMXVyVmVBVG1zQXNDTGg2Ris0b0FqekNkWmUrNjhHYTUxVzQzdEdIK2lMMVh6
            Q1VLVm1VMCszTVJ6MVdNbDVxRngrVFdxU2lvQ054V1NjUlRIRFBLSzBDNmp0VStL
            YlVORC85UlNEeEJzQnhxUWk0bXVjeFNYUFU4VXI1d1hMMWZnM2ZUMHJ4WEVhZndX
            cUZRYVFWVXdBdTE3K2xWTi8yTFgrRjRYQ0dHekRqSnRqQnpjalBYd2l5TFduemJz
            bGZ1dER1N05xenNMbHBINU05OG1mVFJFdGpHMVRTR1V0aitPejhNMS8waGY0MFBT
            bWlFblREb0hwdXNFQ1VwbmJ5emlNSUhJeWMxV05IWVhIZlUvZmRsT2lhdjhOQQpB
            SWFaUnBxa3BIUWlrUU1uZ3duMUNjdTYvM0NFajA0ZDNwamVwRk5WdU5zCi0tLSBw
            c2tyNGVJa1B3QmpvTHY5RlNWQTZZS2c5MGczZEFKaWMvT2twdFVrREZJCoaPmhvT
            IOEGijiLJgsYqmDNC0688LG1lY/LKHRJsfKZvOgbsvEcVaxsyKuIl8efYAzUOwHh
            sZZf4KNepHiYUdk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1fm96eas2guseckhkr9z0cwqs62szyfd3zyfasc0vwsztkvpss02etcrjz9w9qrtapgfxzwc4nq66cp25v7pu5dptas9hheu5ahazjal6vrkxkx8v8st2q6dy5x2fsdr9kvk8twcdr96ttemhujkfm5qvfm22suhmswggzfn0uqfchv9xeuelk6w9qc642q4eadrzh3lj52zuw3k7lqs8w9z2s8gzv2pzekc558f99q7mgedvzup30u4uw36aht06uywpj2j4pm5tmvs9kja0k8wngs42xjgwu6n99gf98jjz3q5zy2pge8pu2qjcezp2xn52kpa5zz0fuz37xm29axjgg4z5s66fq2avvlycqeegmggm8k9wg0n48x2nyvqktjusw9eu0knq49ydykv8z2yc82tzv6n3nn2krnty9vx6mamh5a24kmqp9arkxu2gzly8ygux6k4n3cskkf40w58fuc62ftp8ma6hdtpy8ssyk8p592pjnf60n8pz0x6hpr45c4r7788dhaudeky42r3k8sxcp893hj6aavmgpqftpmte4vj0dxjeuf97apktp7tphp05ngurz804w4waaxcv994z2qjxfszx8namp3ccquch9qx95egnws4nchwxlvwpw9cul6ftnl2ef0g9zlgpkp4q89qz58eyw7g9nganf32wmqvv893zawasjy4s0v2t2hd3tsvn6xjq6jgg88uq9vvfrfkef8p888r9f4c56ghm83r9ky2ppsrh3x40jl448d7zd4de2thpnscxgee242ptmqmjnl87jw6gsjjhyumwnmsug5zedxxd8p2y0wltnee4tyw9jg3nxvpe9q4dljrdm7m7swj9anzsgectgx3zudvp95pdnjc3yppcp38wxx5asfa4ahqfksngpqz2x922rv8rjklnf55ft8rk2y73nh9pcew30j5rgcmatltj8v4zxxxazqllafy4ezjpfv6m4jlcvgfzxk59fgm60gx2qrpe536yq3h2kw9hysthc4vv6emy2f9mn8g80yde2ynags2pmey5n48k0ulzy0sag3sqfk9ku0v9xadt2k0g9n20u6fq8cns4d5twt23kp9yxrqrt9numy9cuxcugsygdwn9q5xyuqx2c9ffcfz55crq33gc3wqpdg4cz5mnzet9zkrz4hf4g4p6ngdtmy5wh5wy6wa948dp42cnxn9tdesfeykq6wxedrqlrznw6zkpz7ffy6n25rwntyjqqns4rqhssefljmavpdusn8rgx9tj66j86vddzepmpf6hsrtty350v6cevysyde2tndrgg38sq0dc0v8y63675pz9a68p0w6jc994k8psad9gwcc3c83tf82scep2xxf5jpnh073vt3q9hdsjqmr0t28luxge6nwqnusctdsmzyfqvdcp2faem24vt4ajeqgcgjlpgjduwa9gxt9jk0dckkecs2u50x60vumjzwe5y9nhztweyqacjqhke3ut9k2ykhqm3up0pg9pvrzup8zeew6smqa9gjahs6jyzw8g8cthvk5ylj5jphzz2fhn6gw8uf30f35sllf3xdw8cdawazz3wf9pmxgjma2crm872nycnqch7xzdc4mq2kdex5jvtpl6x3p374uyttuc8ml25w2jk9cpep36sfm0ssctr6ry5frvyy0zk5kwdve2syre834m8m2r27qnj305jgacdrc2f00n2g0jkltsygl9xvpydrwg67q59ekxtvd0ldfnkjr63nqymzk6ggjp33hkxqhfapr8zcxyf7qr0dv6w26ynytcmut9qqjt766fn8p62ttn3tzaknk5uhvzuvrr5fqs33jldxkjwfsaseql8mqwqlwyxheg6s5fvgggqfsq7rsrvrgcmhl026stqsf770sqaj76l9sekur7l209qhl30svqzvqf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T16:59:03Z"
    mac: ENC[AES256_GCM,data:F+K/27yz3kcQbHPI+rc/QqLACoCPk/ZSWOp04Fnm9bpn7bQwVoCzEEAl1RbbV+S2B4SCayGJDs4IHRP3ltKz6P3AlYooYXdNTk+u13ZBQ9Lg/FQkmmm4hR2t553/3vfU6reuQzaSsC/0Ha31U5tvEtRaJVwkR5Dqd2+gb6sYQEY=,iv:hS9yhRvgh46r+sebA0AApbTvwnByLqKGiuU3ejo1/KU=,tag:LaOUafzL+SYWaXpMQQ3q5w==,type:str]
    version: 3.13.3
